POST http://localhost:8080/challenges
Content-Type: application/JSON

{
"titreChallenge" : "Challenge 7",
"descriptionChallenge" : "Chall 7"
}

###

PUT http://localhost:8080/challenges/6015b93c-fc5e-45bf-92c9-1db239b97637
Content-Type: application/JSON

{
  "titreChallenge" : "Challenge 1 modifié",
  "descriptionChallenge" : "banajsbbsdkdejed"
}

###

GET http://localhost:8080/challenges

###

###

GET http://localhost:8080/challenges/today

###


DELETE http://localhost:8080/challenges/6015b93c-fc5e-45bf-92c9-1db239b97637

###

POST http://localhost:8080/challenges/historique

###







